# Generated by Django 2.1.5 on 2019-02-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_ques_choices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions_library',
            table='Questions_library',
        ),
    ]
