# Generated by Django 2.1.5 on 2019-02-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_survey_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_result',
            name='answer',
            field=models.CharField(max_length=256),
        ),
    ]
